### ISSUE TITLE
Enkoodaus ISO-8859-1 -> UTF-8

### ISSUE THREAD

**Issue by linjaaho** [avoimet-oppimateriaalit-ry/calculus-fennicus#1]
Tiedostojen enkoodauksen voisi muuttaa 2010-luvulle, sitten kun joku ehtii. Vaatii myös pientä säätöä LaTeXin kanssa.

**Comment by kenkku** [comment]
https://github.com/avoimet-oppimateriaalit-ry/calculus-fennicus/pull/2
