### ISSUE TITLE
Pdf dist -kansioon tms.

### ISSUE THREAD

**Issue by omahlama** [avoimet-oppimateriaalit-ry/calculus-fennicus#3]
Tänne voisi liittää valmiin pdf:n `dist` kansioon niille käyttäjille, jotka haluavat vain lukea vanhaa kunnon oppikirjaa ilman, että täytyy ensin säätää latexin kanssa.

**Comment by Ape** [comment]
Ehdotan, että pdf siirretään pois Git-reposta. Oikeampi paikka binäärijulkaisuille on esimerkiksi liitetiedostojen lisääminen releaseen / tagiin. Tässä jotain infoa: https://github.com/blog/1547-release-your-software
